### ISSUE TITLE
Use F# functions instead of delegates

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#20]
> Use F# functions (int->int->string) instead of delegates (System.Func<int,int,string>) for the signatures. Delegates are not needed in Fable 1.0, as F# lambdas don't compile as nested functions any more.

copied from #1 [comment](https://github.com/fable-compiler/ts2fable/issues/1#issue-217374509)

@alfonsogarciacaro @ncave My understanding that this wasn't yet possible in Fable because it is not yet possible with the FSharp.Compiler.Service. A workaround may be to create extension methods that are F# functions that call the delegates. We could put a `Func` suffix on the intermediate delegates or something similar.

**Comment by alfonsogarciacaro** [comment]
@ctaggart Yes, FCS still expresses F# functions as nested lambdas in F# AST however now Fable [flattens them into multi-argument functions](http://fable.io/repl/#?code=let%20test()%20%3D%0A%20%20let%20f1%20x%20y%20z%20%3D%0A%20%20%20%20x%20%2B%20y%20%2B%20z%0A%20%20%20%20%0A%20%20let%20f2%20x%20y%20%3D%0A%20%20%20%20printfn%20%22Hello!%22%0A%20%20%20%20fun%20z%20-%3E%20x%20%2B%20y%20%2B%20z%0A%20%20%20%20%0A%20%20f1%2C%20f2%0A%20%20%0A%20%20%0Alet%20test2()%20%3D%0A%20%20let%20f1%2C%20f2%20%3D%20test()%0A%20%20%0A%20%20let%20f1%20%3D%20f1%205%0A%20%20f1%206%207%20%7C%3E%20printfn%20%22RESULT1%3A%20%25i%22%0A%20%20%0A%20%20let%20f2%20%3D%20f2%203%204%0A%20%20f2%202%20%7C%3E%20printfn%20%22RESULT2%3A%20%25i%22%0A%20%20%0Atest2()%0A&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2) so you can send them to an external library and invoke them as normal JS functions (this has complicated Fable a bit, but it was the #1 user request for easy interop with JS).

As you can see in the linked example, Fable will try to wrap the lambdas when these are curried and in difficult cases it will build a [dynamic CurriedLambda](https://github.com/fable-compiler/Fable/blob/master/src/js/fable-core/CurriedLambda.ts) that will check the number of arguments being applied at runtime.

Thanks to users' feedback I think [we've covered most cases](https://github.com/fable-compiler/Fable/blob/master/tests/Main/ApplicativeTests.fs) and that's why it should be safe to use F# functions instead of delegates in the signatures of external types. In fact, that's what users are already doing in bindings created manually. It'd be nice if ts2fable would do this automatically because many users have expressed that the [automatic function to delegate conversion](https://stackoverflow.com/a/42847840/3922220) doesn't work well in all cases.

**Comment by ctaggart** [comment]
fixed by #27
