### ISSUE TITLE
source maps should work for local builds

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#218]
I should be able to open up Visual Studio Code, create a launch definition, and debug into the F# code. It isn't currently working.

Here is a launch.json
``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "name": "ts2fable",
            // "program": "${env:LOCALAPPDATA}/Yarn/Data/global/node_modules/ts2fable/dist/ts2fable.js",
            "program": "C:/Users/camer/fs/ts2fable/dist/ts2fable.js",
            "args": [ "index.d.ts", "ReactNativeMapbox.fs" ],
            "sourceMaps": true
        }
    ]
}
```

**Comment by humhei** [comment]
- [Run WatchCli task](https://github.com/fable-compiler/ts2fable/blob/master/.vscode/tasks.json#L21)
- Set breakpoint in `ts2fable.fs`
- [F5 Launch Cli](https://github.com/fable-compiler/ts2fable/blob/master/.vscode/launch.json#L17)

**Comment by humhei** [comment]
### A bit longer explanation:
Since we switched to webpack
There are two ts2fable.js generated.

1. `dist/ts2fable.js ` : This is generated by `fable-splitter`. We only use dist/*.js for yarn publishing  
2. `build/ts2fable.js`: This is generated by [webpack](https://github.com/fable-compiler/ts2fable/blob/master/tools/webpack.config.cli.js). It includes sourmap info.

**Comment by humhei** [comment]
> // "program": "${env:LOCALAPPDATA}/Yarn/Data/global/node_modules/ts2fable/dist/ts2fable.js",
Should we add sourmap info to global
