### ISSUE TITLE
Problems converting LocalizedStrings.d.ts

### ISSUE THREAD

**Issue by matthid** [fable-compiler/ts2fable#238]
We tried to create bindings for
https://github.com/stefalda/react-localization/blob/master/lib/LocalizedStrings.d.ts

And get the following results:
![image](https://user-images.githubusercontent.com/1866463/42892067-2a7ebc92-8ab1-11e8-86aa-08d7d86c048e.png)

Any idea what happened? Also we tried to fix the error by replacing `JSX.Element` with `React.ReactElement` and then other errors appear which look like F# syntax errors.

**Comment by humhei** [comment]
**Option1:**
How about manually remove `JSX.Element`?
```fsharp
    type Formatted =
        U2<float, string>

```
`JSX` systax is introduced to typescript and javascript
```
class Header extends React.Component {
  render() {
    return (
      <h1>Hello World</h1>
    );
  }
```
But in fable we use fsharp DSL to render react element
**Option2:**
using [ts2fablfe.React.fs](https://github.com/fable-compiler/ts2fable-exports/blob/master/React.fs) but not [Fable.Import.React.fs](https://github.com/fable-compiler/fable-react)(currently **not recommanded** as everything else in the Fable landscape uses Fable.Import.React bindings )
BTW,you can find `module JSX` in 
[react.fs](https://github.com/fable-compiler/ts2fable-exports/blob/master/React.fs#L2536)

**Comment by matthid** [comment]
So I'd download  ts2fablfe.React.fs  and add it to my project, correct?

**Comment by humhei** [comment]
@matthid  I don't recommand using `ts2fable.React.fs`
Because `Elimish`,`Fulma`,`Safe-Stack` are using `Fable.Import.React.fs`

But if you want to be a hacker and ts2fable developer,you can use it(you must do everything youself to hack elmish and other things  (most likely, i will do it) )

So i recommand you to choose the `option1`

**Comment by matthid** [comment]
What we would like to understand is what the general and recommended workflow is to use libraries without existing bindings. It seems documentation around that scenario are a bit missing therefore the question for this very concrete scenario. But it seems like the initial route was the correct one (which is using ts2fable and manually fixing any occurring issues)?

Again thanks and I guess this can be considered as answered.

**Comment by MangelMaxime** [comment]
@matthid In general, when you are using Elmish in your application and want to use React libraries. 

The recommanded way is to write the "special" bindings to keep the same DSL and use functional style. We don't have yet a project to automate this process.

For example, in my app we need to use `react-leaflet` and the binding can be found [here](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.ReactLeaflet/ReactLeaflet.fs)

As you can see it have nothing to look with what ts2fable output.

----

In the case of `LocalizedStrings.d.ts` I don't think it's needed because it isn't providing components for you to use. 

The `JSX.Element` case correspond to:

```fs
 // React components can be used as placeholder values! Useful when using links or customizing style
  strings.formatString(strings.onlyForMembers, <a href="http://login.com">{strings.login}</a>)
  strings.formatString(strings.iAmText, <b>{strings.bold}</b>)
```

And I don't think, you will use this synthax in your project. I think you could remove the `JSX.Element` references in the generated binding. 

I think you can use the library to retrieve the string and directly use it in your views.

Pseudo code:

```fs

let strings : LocalizedStringsFactory = LocalizedStringsFactoryStatic.Create((* here you pass the records for the strings*))

let view model dispatch =
    p [ ]
        [ str (strings.formatString(strings.question, strings.bread, strings.butter)]
```

**Comment by matthid** [comment]
@MangelMaxime The only problem with your pseudo code is that `LocalizedStringsFactory` seems to have no methods defined on it:

```fsharp
    type [<AllowNullLiteral>] LocalizedStrings<'T> =
        interface end

    type [<AllowNullLiteral>] LocalizedStringsFactory =
        interface end

    type [<AllowNullLiteral>] LocalizedStringsFactoryStatic =
        [<Emit "new $0($1...)">] abstract Create: props: GlobalStrings<'T> -> LocalizedStringsFactory
```

It looks like it couldn't handle

```typescript
    export type LocalizedStrings<T> = LocalizedStringsMethods & T;

    interface LocalizedStringsFactory {
        new <T>(props: GlobalStrings<T>): LocalizedStrings<T>;
    }

    var LocalizedStrings: LocalizedStringsFactory;
    export default LocalizedStrings;
```

Sadly I don't really understand the TypeScript syntax. In fact shouldn't return `Create` the type `LocalizedStrings<T>`? And I don't think `LocalizedString<T>` should be empty oO
