### ISSUE TITLE
Fable.Core 3.0

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/ts2fable#298]
The project should be updated to deal with the changes of Fable.Core 3.0.
Could someone list the necessary changes and some pointers on how to do this?

**Comment by humhei** [comment]
Thanks for your positive action

https://github.com/fable-compiler/Fable/issues/1580
type tests interfaces may fail after update to Fable.Core3.0 while ts2fable used a lot

**Comment by MangelMaxime** [comment]
Type tests interfaces are not working since Fable 2 or 2.1 release so we should just not generate them ;)

Changes are 

- `Fable.Import.JS` renamed into `Fable.Core.JS`
- `Fable.Import.Browser` has been splitted into several smaller packages. I am not sure if `Browser.Types.*` is robust enough to get access to the types information or if we need to create a representation of the types to know which namespace to require.

**Comment by MangelMaxime** [comment]
- `Array<'T>` is now `array<'T>`

**Comment by MangelMaxime** [comment]
- `JS.Error` is now `System.Exception` *needs to be confirmed by @alfonsogarciacaro*

**Comment by alfonsogarciacaro** [comment]
Yes, I can confirm all points by @MangelMaxime. I think `open Browser.Types` should be enough to replace `open Fable.Import.Browser` in the bindings.

**Comment by et1975** [comment]
> JS.Error is now System.Exception

This is now a bit cumbersome - ts2fable still declares an error as an interface, so simply switching `inherits` to `System.Exception` doesn't work.

**Comment by reginaldlouis** [comment]
Any ETA?

**Comment by 0x53A** [comment]
Some typescript declarations inherit from ``Array<T>`` or ``ReadonlyArray<T>``.

Can I inherit them from ``IList<T>`` and ``IReadOnlyList<T>``?
