### ISSUE TITLE
create new types for TypeLiterals

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#93]
There are a lot of TypeLiterals. They are essentially anonymous types that will need to be give new names. typescript.d.ts has several. There are two unioned here:

``` ts
    /** ES6 Iterator type. */
    interface Iterator<T> {
        next(): {
            value: T;
            done: false;
        } | {
            value: never;
            done: true;
        };
```

Any suggestions on how we should name the created types? IteratorTL1 & IteratorTL2?

**Comment by ctaggart** [comment]
If this is duck typing, then may be we need to leave it as `obj`.

**Comment by MangelMaxime** [comment]
Objet seems fine to me here

**Comment by alfonsogarciacaro** [comment]
The case of `Iterator` is very complicated (it also contains `never` which is another headache) and I wouldn't worry too much about it because Fable maps F# `seq` to JS `Iterable`. About other type literals we can just use the literal type (e.g. `done: bool`) or we could generate types with a special attribute and let Fable check the literal value during compilation. Something like:

```fsharp

type [<CheckLiteral(true)>] TrueLiteral =
  | TrueLiteral
  // Implement op_ErasedCast so we can use the (^!) operator
  static member op_ErasedCast(x: bool) = TrueLiteral
```

But I'm afraid in most cases the literal types would be combined with TS union and object types (as in the case of `Iterator`) so I'm not sure how far we can go with type checking in F#.

**Comment by ctaggart** [comment]
The TypeLiterals I wanted to cover for now are in #121.
